# Generated by Django 6.0.2 on 2026-08-20 18:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_per_term_min', models.PositiveIntegerField(default=55000)),
                ('fees_per_term_max', models.PositiveIntegerField(default=90000)),
                ('tagline', models.CharField(default='Invest in skills that last a lifetime', max_length=200)),
            ],
            options={
                'verbose_name': 'Fee Configuration',
                'verbose_name_plural': 'Fee Configuration',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media', models.FileField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('category', models.CharField(choices=[('event', 'Event'), ('workshop', 'Workshop'), ('community', 'Community')], max_length=20)),
                ('date', models.DateField()),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('tech', 'Tech'), ('education', 'Education'), ('ops', 'Operations'), ('leadership', 'Leadership')], default='tech', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('founder', 'Founder & CEO'), ('instructor', 'Instructor'), ('lead', 'Programme Lead'), ('support', 'Support Staff')], default='instructor', max_length=20)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('initials', models.CharField(blank=True, max_length=3)),
                ('stripe', models.CharField(choices=[('teal', 'Teal'), ('gold', 'Gold'), ('navy', 'Navy'), ('purple', 'Purple')], default='teal', max_length=10)),
                ('credentials', models.CharField(blank=True, max_length=500)),
                ('specialisms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text="E.g. 'Parent of student', 'Student", max_length=100)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avatar_initials', models.CharField(blank=True, help_text='Auto-filled from name if left blank', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin'), ('instructor', 'Instructor')], default='student', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('invite_token_used', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Student / participant name')),
                ('certificate_type', models.CharField(choices=[('completion', 'Certificate of Completion'), ('achievement', 'Certificate of Achievement'), ('participation', 'Certificate of Participation'), ('excellence', 'Certificate of Excellence')], default='completion', max_length=20)),
                ('start_date', models.DateField(verbose_name='Program Start Date')),
                ('completion_date', models.DateField(verbose_name='Date of completion')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Certificate issue date')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], default='valid', max_length=10)),
                ('revoked_reason', models.CharField(blank=True, help_text='Internal note — never shown on the public verification page.', max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/')),
                ('verification_url', models.URLField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('revoked', 'Revoked'), ('restored', 'Restored to valid'), ('edited', 'Edited')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='pages.certificate')),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('other_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('custom_course_interest', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True)),
                ('track', models.CharField(blank=True, choices=[('igcse', 'IGCSE / Cambridge'), ('cbc', 'CBC / CBE'), ('none', 'No preference')], max_length=10, null=True)),
                ('cohort_label', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_bracket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.agebracket')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.enrollmentstatus')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='pages.enrollment'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='pages.level'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('term_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_currency', models.CharField(default='KES', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('hero_copy', models.TextField(blank=True)),
                ('what_they_build', models.JSONField(blank=True, default=list)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('certificate_name', models.CharField(blank=True, default='i-CODE Certificate of Completion', max_length=150)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('age_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='pages.agebracket')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='pages.level')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='programs',
            field=models.ManyToManyField(to='pages.program'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='pages.program'),
        ),
        migrations.CreateModel(
            name='TermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_min', models.PositiveIntegerField(help_text='Minimum fee in KES. Use same value as max for fixed price.')),
                ('fee_max', models.PositiveIntegerField(help_text='Maximum fee in KES. Set equal to min if no range.')),
                ('program_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='pages.programtype')),
            ],
            options={
                'ordering': ['program_type__order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='pages.program')),
                ('tool_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='pages.tooltype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id_entered', models.CharField(max_length=24)),
                ('result', models.CharField(max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('matched_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='pages.certificate')),
            ],
            options={
                'verbose_name': 'Verification attempt',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='pages_certi_certifi_3cfdd2_idx'),
        ),
    ]
