# Generated by Django 6.0.2 on 2026-03-30 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration', models.CharField(help_text='e.g. "8 weeks"', max_length=50)),
                ('program_type', models.CharField(choices=[('coding', 'Coding'), ('robotics', 'Robotics'), ('cybersecurity', 'Cybersecurity'), ('drone', 'Drone Training'), ('ai', 'Artificial Intelligence'), ('flexible', 'Flexible Schedules')], max_length=20)),
                ('level', models.CharField(choices=[('all', 'All Levels'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='all', max_length=20)),
                ('age_min', models.PositiveSmallIntegerField(default=7)),
                ('age_max', models.PositiveSmallIntegerField(default=18)),
                ('instructor_name', models.CharField(help_text='Instructor full name (no login system)', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage Popular Classes section')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='I-code', max_length=100)),
                ('hero_heading_accent', models.CharField(default='Inspiring Kids', help_text='The orange-coloured first part of the hero heading', max_length=120)),
                ('hero_heading_main', models.CharField(default='to Build the Future with Technology', max_length=200)),
                ('hero_subtext', models.TextField(default='I-code is a hands-on in-person tech school for young innovators aged 7–18. We offer classes in Coding, Robotics, AI, Cybersecurity, and Drone Training — from beginner to advanced.')),
                ('footer_description', models.TextField(default='Inspiring young innovators aged 7–18 to build the future through hands-on tech education.')),
                ('contact_email', models.EmailField(default='contact@icode.com', max_length=254)),
                ('phone_number', models.CharField(default='+1 (555) 123-4567', max_length=30)),
                ('address', models.CharField(default='Open Mon–Fri 8:30am–8:30pm · Weekends 8:30am–4pm', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Students Enrolled"', max_length=80)),
                ('value', models.CharField(help_text='e.g. "500+" or "98%"', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('child_name', models.CharField(blank=True, help_text="Child's name if enrolling on behalf of someone", max_length=120)),
                ('child_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pages.course')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(help_text='Not shown publicly', max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Tick to publish this review publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Override title, e.g. "Robotics Workshop — Beginners"', max_length=200)),
                ('instructor_name', models.CharField(max_length=120)),
                ('scheduled_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='pages.course')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('occupation', models.CharField(blank=True, help_text='e.g. "Parent of Alex, age 10"', max_length=120)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage')),
                ('is_approved', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='pages.course')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
