# Generated by Django 6.0.2 on 2026-04-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
