# Generated by Django 6.0.2 on 2026-06-27 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_program_age_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('founder', 'Founder & CEO'), ('instructor', 'Instructor'), ('lead', 'Programme Lead'), ('support', 'Support Staff')], default='instructor', max_length=20)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('initials', models.CharField(blank=True, max_length=3)),
                ('stripe', models.CharField(choices=[('teal', 'Teal'), ('gold', 'Gold'), ('navy', 'Navy'), ('purple', 'Purple')], default='teal', max_length=10)),
                ('credentials', models.CharField(blank=True, max_length=500)),
                ('specialisms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text="E.g. 'Parent of student', 'Student", max_length=100)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avatar_initials', models.CharField(blank=True, help_text='Auto-filled from name if left blank', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='preferred_registration_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='preferred_start_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='registration_timeline',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cohort_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='referral_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='track',
            field=models.CharField(blank=True, choices=[('igcse', 'IGCSE / Cambridge'), ('cbc', 'CBC / CBE'), ('none', 'No preference')], max_length=10, null=True),
        ),
    ]
