# Generated by Django 6.0.2 on 2026-05-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media', models.FileField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbs/')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('category', models.CharField(choices=[('event', 'Event'), ('workshop', 'Workshop'), ('community', 'Community')], max_length=20)),
                ('date', models.DateField()),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
