# Generated by Django 6.0.2 on 2026-06-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teammember_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='dept',
            field=models.CharField(choices=[('tech', 'Tech'), ('education', 'Education'), ('ops', 'Operations'), ('leadership', 'Leadership')], default='tech', max_length=20),
        ),
    ]
