# Generated by Django 6.0.2 on 2026-08-12 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_teammember_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('robotics', 'Robotics'), ('ai', 'Artificial Intelligence'), ('coding', 'Coding / Programming'), ('bootcamp', 'Bootcamp'), ('competition', 'Competition'), ('corporate', 'Corporate Training'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive programmes are hidden from the certificate creation form but existing certificates keep working.')),
            ],
            options={
                'verbose_name': 'Programme / Course',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin'), ('instructor', 'Instructor')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Student / participant name')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('certificate_type', models.CharField(choices=[('completion', 'Certificate of Completion'), ('achievement', 'Certificate of Achievement'), ('participation', 'Certificate of Participation'), ('excellence', 'Certificate of Excellence')], default='completion', max_length=20)),
                ('completion_date', models.DateField(verbose_name='Date of completion')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Certificate issue date')),
                ('assessment_status', models.CharField(choices=[('passed', 'Passed'), ('pending', 'Pending'), ('not_required', 'Not required')], default='passed', max_length=20, verbose_name='Assessment / project status')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], default='valid', max_length=10)),
                ('revoked_reason', models.CharField(blank=True, help_text='Internal note — never shown on the public verification page.', max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/')),
                ('verification_url', models.URLField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='pages.programme')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('revoked', 'Revoked'), ('restored', 'Restored to valid'), ('edited', 'Edited')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='pages.certificate')),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id_entered', models.CharField(max_length=24)),
                ('result', models.CharField(max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('matched_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='pages.certificate')),
            ],
            options={
                'verbose_name': 'Verification attempt',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='pages_certi_certifi_3cfdd2_idx'),
        ),
    ]
