# Generated by Django 6.0.2 on 2026-08-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_certificate_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='programme',
        ),
        migrations.AddField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='pages.program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='pages.level'),
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
