# Generated by Django 6.0.2 on 2026-05-13 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('other_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('preferred_registration_date', models.DateField(blank=True, null=True)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('custom_course_interest', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_bracket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.agebracket')),
                ('programs', models.ManyToManyField(to='pages.program')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.enrollmentstatus')),
                ('registration_timeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.registrationtimeline')),
            ],
        ),
    ]
