# Generated by Django 6.0.2 on 2026-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='program',
            name='age_range',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.CharField(default='💡', max_length=10),
        ),
    ]
