# Generated by Django 6.0.2 on 2026-05-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_program_options_program_age_range_program_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='icon',
        ),
    ]
