# Generated by Django 6.0.2 on 2026-05-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_program_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_per_term_min', models.PositiveIntegerField(default=55000)),
                ('fees_per_term_max', models.PositiveIntegerField(default=90000)),
                ('tagline', models.CharField(default='Invest in skills that last a lifetime', max_length=200)),
            ],
            options={
                'verbose_name': 'Fee Configuration',
                'verbose_name_plural': 'Fee Configuration',
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_min', models.PositiveIntegerField(help_text='Minimum fee in KES. Use same value as max for fixed price.')),
                ('fee_max', models.PositiveIntegerField(help_text='Maximum fee in KES. Set equal to min if no range.')),
                ('program_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='pages.programtype')),
            ],
            options={
                'ordering': ['program_type__order'],
            },
        ),
    ]
